### ISSUE TITLE
Import/Export Settings

### ISSUE THREAD

**Issue by jdanthdavis** [pajlads/DinkPlugin#152]
An option to export/import settings would be extremely helpful. Especially, when using custom messages for notifications. Something similar to how the Radius Markers plugin works.

![import-export-example](https://user-images.githubusercontent.com/87504521/215797380-3996fc8f-b2e5-44ee-a363-0efb47866884.png)

**Comment by iProdigy** [comment]
Since standard runelite plugin configs don't allow arbitrary buttons, we'd have to create a custom plugin panel (as Radius Markers has done) & I'd want to have more use cases for this panel than just import/export

Technically, the pure-config approach is possible through the following hack, but it's likely to be too confusing to users (so I'm not particularly inclined to implement it): create a boolean checkbox config for `import` and a separate boolean checkbox config for `export` - when the value of either is changed, use `ConfigChanged` event to perform our logic. This is confusing because the boolean state is meaningless to the user, but they might to try to infer meaning (e.g., checkbox could move from on to off & correctly perform the copy-to-clipboard action, but user may be confused if it actually worked)

**Comment by iProdigy** [comment]
This feature will require some dank implementation details, but it may be worth it:

* On settings import, the config panel will not automatically update (runelite limitation), so we will send a chat message asking the user to restart (if they want the panel updated)
* On settings import, we will want to deduplicate any urls (via `LinkedHashSet`)
* A settings import could include overrides while the current config has no overrides (only primary). In this case, we should copy the current primary urls to the overrides field & append the imported overrides
* Since we are not allowed to use reflection within plugins, whenever a new config field is added, we'll have to update the import handler to be able to write values for the new config key

**Comment by jdanthdavis** [comment]
@iProdigy Very much appreciated for this new feature. My lazy friends send their thanks as well. You all our doing fantastic with this plugin. Keep up the good work!

**Comment by equirs** [comment]
> we figured out you just have to close the Dink settings menu for the panel to update

just a thought on this: you should probably be able to tell the panel to refresh itself after an import/export, so no extra instructions to the user should be necessary

**Comment by iProdigy** [comment]
> just a thought on this: you should probably be able to tell the panel to refresh itself after an import, so no extra instructions to the user should be necessary

The last time I checked, there unfortunately was no such method... technically this could be hacked together with reflection but we are not allowed to do reflection as a hub plugin :/

**Comment by equirs** [comment]
ah, you're right, there is no way to access that panel normally. unfortunate

**Comment by iProdigy** [comment]
This is now possible in Dink v1.3.0, which is already updated in the [plugin hub](https://github.com/runelite/plugin-hub/pull/3873)!

You can find the documentation for `::dinkexport`/`::dinkimport` here: https://github.com/pajlads/DinkPlugin#chat-commands
