### ISSUE TITLE
Extra information for 'QUEST' type not provided

### ISSUE THREAD

**Issue by APKiwi** [pajlads/DinkPlugin#190]
In the readme the 'extra' detail for quests is supplied as such:
```{
  "content": "%USERNAME% has completed a quest: %QUEST%",
  "extra": {
    "questName": "Dragon Slayer I",
    "completedQuests": 22,
    "totalQuests": 156,
    "questPoints": 44,
    "totalQuestPoints": 293
  },
  "type": "QUEST"
}
```

However the extra fields such as 'completedQuests', 'questPoints' are not submitted:

```
0|KX  | 19/03 15:50: API Submission Type QUEST
0|KX  | 19/03 15:50: Player_Name Ommitted
0|KX  | 19/03 15:50: Account_Type HARDCORE_IRONMAN
0|KX  | 19/03 15:50: Extra { questName: "Gertrude's Cat" }
```

**Comment by Felanbird** [comment]
The README is updated because of https://github.com/pajlads/DinkPlugin/pull/178 - there has not yet been a stable release + update to the plugin that's available on runelite with these changes.

The README for the stable version does not state this change yet https://runelite.net/plugin-hub/show/dink

**Comment by APKiwi** [comment]
Great thanks for the explanation! That also covers the same with collection logs, etc that I encountered. Feel free to close
