### ISSUE TITLE
Collection Log wait for Popup

### ISSUE THREAD

**Issue by MichaelAGordon** [pajlads/DinkPlugin#249]
I would like the screenshot to also see the popup of the new collection log in the screenshot that is sent to discord, or at least have it be an option we can change

**Comment by Felanbird** [comment]
I would only be fine with this being added, if we made it an _or_ thing coding wise. 

When the related setting for this is enabled, `COLLECTION_LOG_NOTIFICATION` receives +2 value, meaning when the varbit is either `2` or `3`, while only having the normal notification on, the varbit is `1`.

I'd like for people only using the normal chat notif, not to experience longer notification time due to popup users wanting the popup.
