### ISSUE TITLE
discord notification keeps saying i level up all skills?

### ISSUE THREAD

**Issue by Woodoki** [pajlads/DinkPlugin#262]
Used the plugin for months and changed zero settings since. It keeps sending all skill level up notifications every now and then when I log in spamming the discord channel. https://gyazo.com/53ed0a19bf361c3c2053daf4e3ad23a5 

started on 6-27 for me but my teammate has one just like it from 6-21

**Comment by Felanbird** [comment]
Can you upload your `client` file
![image](https://github.com/pajlads/DinkPlugin/assets/41973452/847cd132-29ed-40c0-be21-ed7585983cbe)

Also, can you make sure to confirm the friend's notif is from 6/21 - if it's 6/24 that would change what we look for.

**Comment by APKiwi** [comment]
Can you confirm if you've just logged in (looks to be correct), coming from a PvP Arena world? This behavior is consistent with other notifier plugins, and our experience in dink. We have filtered specifically these notifications server side.

**Comment by Woodoki** [comment]
So odd theory Tried closing the client and opening it a few times got nothing. So I went back to mlm got it every time. Might have something to do with just that area or a different plugin causing issues there? 

[client.log](https://github.com/pajlads/DinkPlugin/files/11915413/client.log)

**Comment by pajlada** [comment]
We might be able to force a dev to go into that accursed place with a development build to see if we can reproduce it

**Comment by Felanbird** [comment]
> or a different plugin causing issues there?

This was my idea as well, the reason I wanted to see if it was 6/24 was because the most recent 3d-weather build has been causing extreme issues for people, and I wasn't able to pinpoint the fog in your screenshot so I thought it might be that, but I see now from your logs it's just 117.

But, unfortunately I'm not able to replicate this issue even in MLM, so the thought process that it's another plugin is likely true.

Do you mind creating and switching to a new profile, downloading `Dink` and giving it basic setup and see if you can still replicate the issue? It's still possible it's still an issue on our end, but it would be nice to confirm either way.
![image](https://github.com/pajlads/DinkPlugin/assets/41973452/088360a6-857f-437a-b413-d4621eea2087)

**Comment by Woodoki** [comment]
still happens. https://gyazo.com/1cf4705f0a17fcf999c12af9068788de https://gyazo.com/d571d896d3aaae23a7b0ee441dc975bb https://gyazo.com/902ba3fbf2385eae9c047ee2974160c3 

I checked send images and min level to 80 same as my other profile but having it set to default still made it happen.
[client.log](https://github.com/pajlads/DinkPlugin/files/11919703/client.log)

**Comment by pajlada** [comment]
I was able to reproduce the issue, somehow only when standing inside MLM.
This includes the issue @APKiwi mentioned, hopping from pvp world or speedrunning worlds.

By increasing the delay of the XP initialization from 200ms to 1s, both issues seem to be fixed

@Woodoki Just as a heads up, your discord webhook URL is leaked in some of the pictures you shared, so you might want to recreate those if you care

Thanks for reporting the issue & helping us debug it!

**Comment by Woodoki** [comment]
pog glad i could help

**Comment by iProdigy** [comment]
This will be fixed in the next Dink release - if you would like to use the patched version today, you can run our nightly jar build: https://github.com/pajlads/DinkPlugin/releases/tag/nightly-build

**Comment by Felanbird** [comment]
Also it might not happen if you login near the entrance/exit to MLM so you could just do that, as that's where I was when I mistakenly confirmed it _not_ happening.
