### ISSUE TITLE
Loot bug: Chromium ingot - Vardorvis

### ISSUE THREAD

**Issue by CrypexHD** [pajlads/DinkPlugin#281]
Chromium ingot not showing up in discord notifications when dropped from Vardorvis

**Comment by iProdigy** [comment]
Loot notifications from the new DT2 bosses can be inconsistent for reasons out of our control; the base RuneLite loot tracker sometimes misses these loot events due to some quirks in how jagex implemented these drops (the RL team is actively developing workarounds, though). 

That said, other Dink users *have* had success with Chromium ingot notifications. If you have `Min Value` configured, be sure you have wiki prices enabled in RuneLite settings: 
![image](https://github.com/pajlads/DinkPlugin/assets/8106344/02909a81-dccb-4e8a-a689-336a61223266)

**Comment by iProdigy** [comment]
@CrypexHD do you recall whether Vardorvis was in the middle of the spike-summoning dance at the time of the kill (when the ingot was dropped)?

**Comment by CrypexHD** [comment]
No, I do not sorry. The first Ingot did not even show up in runelite loot tracker. But the later ones does, and pushes notifications to discord.
