### ISSUE TITLE
Include league messages in a separate notifier type

### ISSUE THREAD

**Issue by APKiwi** [pajlads/DinkPlugin#356]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Could we potentially have a league-specific task completion notification, separate (in a new notifier/category) from the rest of the existing notifications?

Could we also confirm that there is an “account type” label of something league specific to organise notifications as desired?

I don’t think anyone has the exact syntax yet but this is from last trailblazer:
![IMG_4774](https://github.com/pajlads/DinkPlugin/assets/13660274/faceae67-981e-4896-9d32-f39e38e7cc67)

**Comment by Felanbird** [comment]
I've been thinking about if/how Dink will work in leagues and also what the smartest way to get changes in would be.

It's more or less accepted that once leagues starts merging of hub plugins will basically drop to 0 so I'd like to get some more changes #345 #347 #351 #352 into our currently open PR https://togithub.com/runelite/plugin-hub/pull/5115 and then work from there.

After that the question is wanting overhaul the task notifier, or create a new one for a seasonal event, without any confirmation that the changes are necessary/will work. I personally feel like the answer is probably no, but I'm definitely not against marking payloads with this information if possible. 

If there's a way to at least simulate what we think will be necessary (looking at old leagues PRs to other plugins) and creating a PR of what we think is necessary to make sure the current notifier works, then I'd have no problem day1 testing and pestering Adam to review&merge a release. Otherwise we'll do the same day1 much-smaller PR for adding the information necessary.
