### ISSUE TITLE
Kill count for new collection log entries 

### ISSUE THREAD

**Issue by TomBolks** [pajlads/DinkPlugin#371]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

If available and possible add the kill count and monster that dropped the new collection log entry.

### Reasoning

It would be nice to see the information since some items can be dropped by multiple bosses and to see if someone is getting spooned

**Comment by iProdigy** [comment]
Actually this is tricky since the collection event has no idea of the source of the item. Accordingly, we probably need to store the loot table of every NPC, which is blocked like #139 due to incomplete data scraping described in https://github.com/pajlads/DinkPlugin/pull/141#issuecomment-1452902551

**Comment by iProdigy** [comment]
Relevant edge cases:
* clue casket opened at same time as npc kill
* random event reward received at same time
* barrows chest count
* tempoross
* wintertodt
* cox
* toa
* tob
* etc.

**Comment by iProdigy** [comment]
Probably good enough: if npc killed within same second of collection notif & no clue casket opened in that period, attribute item to npc
