### ISSUE TITLE
Screen freezes for a split second every time

### ISSUE THREAD

**Issue by Chryma** [pajlads/DinkPlugin#377]
### Checklist

- [X] I'm reporting a problem with Dink
- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking reports

### Describe your issue

Any time I get a level or trigger Dink, my game will freeze for a split second (presumably to take the screenshot?), is there any way to stop this from happening or any troubleshooting steps I can take?

### Runelite Logs

[client.log](https://github.com/pajlads/DinkPlugin/files/13483672/client.log)

### Runelite Version

1.10.17

**Comment by Felanbird** [comment]
Do you mind trying a profile with only dink? You have a very large amount of hub plugins

**Comment by Chryma** [comment]
The screenshots are between 4 and 8mb

Doing a completely blank profile except for dink does not cause the issue, so it's likely some kind of plugin conflict.. Are there any easy ways to diagnose or trigger dink manually after I disable a bunch to see if I can figure out what's causing it?

**Comment by Felanbird** [comment]
> Doing a completely blank profile except for dink does not cause the issue, so it's likely some kind of plugin conflict.. Are there any easy ways to diagnose or trigger dink manually after I disable a bunch to see if I can figure out what's causing it?

This issue sounds very much like the issue people get when they crash the client due to an OOM, but in your case you just happen to freeze instead of crashing. 
It's not explicitly a problem with any plugin that takes screenshots, there's just a bit-more-than-usual amount of memory being used at the exact moment when a screenshot is taken.

I strongly believe this to be the problem since you have 157 hub plugins, which could easily be using enough memory to cause the problem I mentioned above.

As for debugging, you could just replicate this problem by setting the hotkey in the `Screenshot` plugin and pressing it, or maybe the hub plugin ` random screenshot`

**Comment by pajlada** [comment]
You could set your loot threshold to 1gp and open bird nests, or use the grand exchange notifier & sell/buy something on the grand exchange

**Comment by iProdigy** [comment]
Do you happen to have the `Screenshot Scale` advanced config setting set to some value below 100%? (your screenshot sizes shouldn't be large enough to trigger our automatic rescaling, but perhaps you have forced rescaling on)

If so, are your freezes are brief as the micro-stutter in this clip? https://clips.twitch.tv/BovineInnocentGrasshopperOSkomodo-CCpG409ql3J_gpx3
We've [fixed](https://clips.twitch.tv/ScrumptiousDignifiedMeerkatFunRun-TLey4eOmg9b9TdCd) that issue in #378 - but if your freezes last longer (or you haven't enabled forced rescaling), it's probably a memory/gc issue that involves a different unoptimized hub plugin

**Comment by iProdigy** [comment]
Closing since this problem isn't on our end, but feel free to share a memory dump & I can investigate which other hub plugin is consuming excessive resources to trigger this issue
