### ISSUE TITLE
Dynamic config ursername parameter

### ISSUE THREAD

**Issue by RobinLaevaert** [pajlads/DinkPlugin#561]
### Checklist

- [X] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Our clan has the issue that sometimes people join, import the dink config, leave the clan after a while and then be toxic enough to leave the webhook URLs in their dink config.

At the moment I have a discord bot that reads every message that dink posts, searches for the matching rsn's and deletes the message if needed.

Instead of doing that or always manually changing the webhooks I had the idea of; why not use dynamic config url and filter out the rsn there.
That way only I need to update the webhooks in the API and all our members their dink will automatically be updated.

**Comment by iProdigy** [comment]
The dynamic config is imported *before* the user has logged in
Also client-side checks may not be ideal when dealing with toxic users

Instead you should create a custom webhook handler that forwards incoming POST requests to the Discord webhook depending on the player metadata in the request body. Then, users would point Dink at your custom URL instead of directly using a discord webhook. For example, you can achieve this for free with Cloudflare Workers (here's an example handler that achieves a different task: https://gist.github.com/iProdigy/53654691a76679221a74fd442dea068a)

**Comment by iProdigy** [comment]
Also, imported urls from the dynamic config are *merged* with the existing urls (rather than outright replaced), so an approach that includes the player name during the dynamic config request would not be able to remove the urls the former clan member had already received

For the custom webhook handler approach, feel free to read our docs: https://github.com/pajlads/DinkPlugin/blob/master/docs/json-examples.md (you will want to use `playerName` or `dinkAccountHash`)
